### ISSUE TITLE
SharingServer Library

### ISSUE THREAD

**Issue by remusrg** [Microsoft/HoloToolkit#14]
Is there any reason why SharingServer class cannot be included in the sharing library that the client devices use? Also, did you guys think about a P2P version of the SharingServer (and maybe other classes like the lobby/etc) that would take advantage of the ReplicaManager2 and FullyConnectedMesh2 classes available in Raknet?

I am thinking of using the sharing library for a project that combines Holo and PC/tablet but I'd like to move away from a dedicated server model. How far off am I?

**Comment by jwittner** [comment]
I'm finding use cases for this as well.

**Comment by jwittner** [comment]
I'm thinking I'll add a new lib project that absorbs all the Source of SessionServer project except main.cpp.
