### ISSUE TITLE
 Unsafe code requires the `unsafe' command line option to be specified

### ISSUE THREAD

**Issue by yosun** [Microsoft/HoloToolkit#18]
What's with all the unsafe code?

**Comment by yosun** [comment]
https://gyazo.com/8fc9d2982f11b673c338d9f115491523

**Comment by jwittner** [comment]
Hi! Looks like maybe you embedded the HoloToolkit-Unity/Assets/HoloToolkit folder into your own project? I believe this will happen if you don't include the *.rsp files located in HoloToolkit-Unity/Assets folder.

See here: https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets

**Comment by jwittner** [comment]
It also looks like maybe you wanted to post this to the HoloToolkit-Unity project instead of here?

**Comment by yosun** [comment]
ah, so is this the reason why the kit isn't just a .unitypackage? 

also - might be helpful to note this in readme that the custom .rsp files are required etc
