### ISSUE TITLE
Sharing relies heavily on outdated Windows SDK version 10.0.10240.0

### ISSUE THREAD

**Issue by jwittner** [Microsoft/HoloToolkit#21]
From a clean install of Visual Studio Update 3 with the newest Windows SDK (version 10.10.10586.0) there are failures to build (HoloToolkit/Sharing/BuildAll.bat)  in numerous dependencies.

Was thinking we'd just remap every project, leaving the minimum at the current where possible.

**Comment by jwittner** [comment]
Had to 'Allow Unsafe Code' in SessionManagerUniversal.UI for the ARM build as well.

**Comment by jwittner** [comment]
Any ideas on the below errors? @alexdrenea?

> 2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2551,5): e
>        rror APPX0104: Certificate file 'SessionManagerUniversal.UI_TemporaryKey.pfx' not found. [C:\Users\jowitt\Source
>        \HoloToolkit\Sharing\Src\Projects\SessionManagerUniversal.UI\SessionManagerUniversal.UI.csproj]
>      2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(2551,5): e
>        rror APPX0107: The certificate specified is not valid for signing. For more information about valid certificates
>        , see http://go.microsoft.com/fwlink/?LinkID=241478. [C:\Users\jowitt\Source\HoloToolkit\Sharing\Src\Projects\Se
>        ssionManagerUniversal.UI\SessionManagerUniversal.UI.csproj]

**Comment by alexdrenea** [comment]
I was just looking at the above comment. My git status shows no changes and I have the allow unsafe code flag set in ARM... I think I have to reset my workspace

**Comment by jwittner** [comment]
@alexdrenea Very strange. When I check the box I get this line `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` added to my csproj. When I look at your csproj here: https://github.com/alexdrenea/HoloToolkit/blob/master/Sharing/Src/Projects/SessionManagerUniversal.UI/SessionManagerUniversal.UI.csproj

I don't see that line for either of your ARM configurations.

**Comment by alexdrenea** [comment]
I re-cloned the project and I can see it now. I'll have a pull request in a moment.

As for the other items in this issue, do you wan to take care of them in a separate PR after I push my fix?

As for the other errors, they happen only when you try to build a store package because you're missing the signing certificate. As far as I know, you're not supposed to check-in the temporary signing certificate file (SessionManagerUniversal.UI_TemporaryKey.pfx). You will need to regenerate it on your end by going in package.appxmanifest -> Packaging -> Choose Certificate and select "Create Test Certificate" from the "Choose certificate" drop down.

**Comment by jwittner** [comment]
Sure, I can keep pushing on the SDK version issues and pull in your change when it comes through. Thanks for the info on the cert too I'll give it a shot and let you know if I run into anything further!

**Comment by alexdrenea** [comment]
PR in.

**Comment by NeerajW** [comment]
@alexdrenea @jwittner thanks both. Merged.

**Comment by jwittner** [comment]
I don't think the underlying issue was resolved, @alexdrenea had a PR that resolved a seperate build issue.

**Comment by jwittner** [comment]
Is there any reason not to remap to the latest?

**Comment by jwittner** [comment]
I'm going to close this issue for now as I've now got all the right Windows SDKs installed - #28 is heading toward documentation which would have helped here.
