### ISSUE TITLE
Enable Network Discovery in SharingClient

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/HoloToolkit#25]
I've noticed that Profiler Tool has a very nice feature to auto discover the server (and other clients) on the current network.
I think that this would be a great feature to have on the SharingClient side so it can be integrated in your HoloLens client app.
I've already made the updates and would like to see what you guys think - I'll submit the PR soon.

The idea is, that if you guys approve, we can update the HoloToolkit-Unity SharingStage class with an AutoDiscover flag that can be used instead of IP. I already have a working version of that too, but I will hold off that PR until you guys confirm that it's a good idea.

**Comment by jwittner** [comment]
Personally I was just talking about doing something like this recently. I worry about the system auto selecting what to connect to, but getting a list would be a great feature I think!

**Comment by NeerajW** [comment]
Totally agree that this is a great idea. Also agree that auto selection will not be ideal :)

**Comment by alexdrenea** [comment]
I think having a UI/option to choose is ideal, but not critical. A lot of users (myself included) would just need an easy way to run a shared experience without worrying about changing the server IP every time. And most will only have one server running in the network so just picking the first will just work.

This PR simply exposes the DiscoveryClient classes to the SharingClient.dll so that it can be used from HoloToolkit-Unity. I can open a new issue there to figure out the best options to expose it to the end-users.

**Comment by jwittner** [comment]
@alexdrenea I think we can leave exposing the list to application developers and that providing them the list is perfect!

**Comment by alexdrenea** [comment]
That sounds good to me!

**Comment by alexdrenea** [comment]
Hey guys, any chance to get this merged. Let me know if you think there's anything missing so I can correct it. I want to go ahead and update some of the HoloToolkit-Unity code and it would be nice to use the real HoloToolkit rather than my forks :smile:

**Comment by jwittner** [comment]
This is merged in now.
