### ISSUE TITLE
Readme update suggestions

### ISSUE THREAD

**Issue by HodgsonSDAS** [Microsoft/HoloToolkit#28]
The readme file should include the prerequisite SDKs and other setup steps as well as the proper build order for each solution.

**Comment by jwittner** [comment]
Agreed!

SDKs currently needed:

- Windows SDK 10.0.10240
- Windows SDK 10.0.10586
- Java SDK 8?

**Comment by HodgsonSDAS** [comment]
_Is_ Java SDK 8 is needed in the current builds?

See I would have never known that! haha

**Comment by jwittner** [comment]
@HodgsonSDAS Not sure if 7 would work, but 8 does for me. I'm hoping people will start adding known requirements here and we can then go update the docs.

**Comment by HodgsonSDAS** [comment]
Well, that explains why I couldn't ever get a successful build! haha

**Comment by HodgsonSDAS** [comment]
Actually doing some digging today and I found the docs.
[https://github.com/Microsoft/HoloToolkit/blob/master/Sharing/Src/Source/Docs/ExtendedDocs/GettingStarted.md](url)
They just seem to be buried deep in folders inside the project. I guess it would be simpler just to extend the Wiki or main ReadMe.md to include links to these.
