### ISSUE TITLE
Support Angle in c#

### ISSUE THREAD

**Issue by JimSEOW** [Microsoft/HoloToolkit#38]
The hololens branch of https://github.com/Microsoft/angle works. 
We hope there is effort to make that works in c#

The UrhoSharp is starting to support Hololens in c#

**Comment by jwittner** [comment]
@JimSEOW thanks a ton for bringing the Angle branch for HoloLens to light! I didn't know that was in progress, pretty cool!

This probably isn't the right forum to request a C# interface - maybe bring up the issue at the Angle Github?

**Comment by JimSEOW** [comment]
@jwittner  We will soon have a C# interface, thanks to someone from Xamarin. 
I think this forum should also consider allowing emerging C# (non-Unity3D) Hololens developers using either UrhoSharp.Hololens.dll or Hololens Angle to take advantage of the HoloToolkit managed libraries. 

Our feedback and participation would help bring new use case to hololens ecosystem. (e.g. Xamarin means more than UWP, but iOS and Android C# devleopers)

**Comment by jwittner** [comment]
I think that's a great idea! Is there anything stopping the developers in question from linking to the HoloToolkit libraries right now?

**Comment by JimSEOW** [comment]
@jwittner  [HoloToolkit4Unity exist](https://github.com/Microsoft/HoloToolkit-Unity) because it is more than just linking to the HoloToolkit libraries.  Likewise, for the two other C# approaches (1)**UrhoSharp.Hololens**, and (2)**WebGL4HoloLens**, we eventually will also need similar dedicated githubs (e.g. **HoloToolkit4WebGL**), more than just samples showing how to do the linking. 

**Why this is critical?** Without spatial mapping and other important functionalities of this library, we could not apply _AI contextual awareness_ to windows store apps developed using UrhoSharp and WebGL. 

**WebGL4Hololens** depends on AngleHoloLens C# interface and [ChakraCore's OpenGL Engine](https://github.com/Microsoft/Chakra-Samples/issues/42)  and [ChakraBridge](https://github.com/Microsoft/angle/issues/86) 

Many of the exciting scientific 3D visualization is currently available in WebGL.js. WebGL4Hololens [c#] will speed up the creation of new Hololens high impact business use cases (e.g. precision medicine and digital health revolution)  

I hope there is a greater cross-functional interactions among the different Microsoft teams to make this happen.
