### ISSUE TITLE
Visual Pairing Question

### ISSUE THREAD

**Issue by egaebel** [Microsoft/HoloToolkit#4]
On the Sharing page here: https://github.com/Microsoft/HoloToolkit/tree/master/Sharing there's a quick description of Visual Pairing which I've copied below

> Visual Pairing
> 
> Connect devices just by looking at them
> 
> One device displays a QR code with connection info and security code
> Other device sees QR code, connects, and validates with security code
> Can also detect location in 3D space using built-in fiducial marker support

My question relates to how visual pairing would be enabled. It sounds as if this is for peripheral devices that have screens? Can you confirm this?

This repo is very fascinating and the documentation is quite good, thanks!

**Comment by NeerajW** [comment]
You can have devices that have screens. You could also have them printed on paper and put them at desired locations.
