### ISSUE TITLE
SessionManager UI Universal

### ISSUE THREAD

**Issue by alexdrenea** [Microsoft/HoloToolkit#6]
Hi guys, 

As I was building my HoloLens shared experience, I quickly found a need to have an app that can monitor the session. I then discovered the SessionManager.UI sample which did exactly that, but as a classic windows app and not UWP. 
So I started building the UWP version and have it at a point where it can join sessions and send some commands to the shared HoloLens expertience.

If there's interest, I can update the UI to match the sample you have and have a pull request for you guys.

Later on, not sure if it's even possible but, would be interesting to try and get it working on ARM as well so you can monitor the session from your phone.

**Comment by NeerajW** [comment]
@alexdrenea this seems like a good idea. This would also open the SessionManager UI to be run on a HoloLens since it will be a UWP. 
I will sync with some more folks and get back to you with a recommendation.

**Comment by NeerajW** [comment]
@alexdrenea spoke with some more people and we all are excited to see this change. 
Please go ahead and issue a pull request.

**Comment by alexdrenea** [comment]
Working on it. Will be out for the next few days but should have something late next week. You can check my fork for the progress so far.

**Comment by alexdrenea** [comment]
Just put up the pull request. There are still a few items that can be improved but I thought it's better to push it now, get some feedback and continue after.
The app is functional and behaves pretty much the same as the desktop version.

**Comment by jwittner** [comment]
I see a matching PR merged, closing.
