### ISSUE TITLE
Remove open-source code that's not needed for HoloToolkit from externally-included projects

### ISSUE THREAD

**Issue by matthejo** [Microsoft/HoloToolkit#68]
External projects that are included in HoloToolkit have source code that is not needed for building HoloToolkit.  In addition, some functionality included in HoloToolkit is covered by other projects and is not needed in HoloToolkit.

* libcurl can be removed.  Projects can use their own copy of libcurl or a number of other download management libraries.
* swig sources can be removed in favor of binaries.
* RakNet has dependent extensions that are not used in HoloToolkit and can be removed.
* AprilTags support can be removed.  For replacement functionality, the HoloLensCompanionKit poster calibration sample can be used.

As part of these changes, HoloToolkit's use of unsafe code can be removed, making projects that use HoloToolkit WACK compliant.

**Comment by jwittner** [comment]
Was this closed by #69?

**Comment by HodgsonSDAS** [comment]
Yeah.

**Comment by AndreV84** [comment]
@jwittner 
Is there apriltags for csharp c#?
is there c# code in the sdk that can be used standalone with c#?

**Comment by jwittner** [comment]
@AndreV84 - not sure about C# April tags support from elsewhere. And I'm not following what you're second question is asking. This issue was closed almost 5 years ago now...
