### ISSUE TITLE
HoloToolkit PlaneFinding doesn't build on latest Windows SDK Visual Studio Update 2

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit#7]
1) Install Visual Studio Update 2 with its default Windows SDK version.
2) Open PlaneFinding.sln.
3) Build Solution

result: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB8036: The Windows SDK version 10.0.10502.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
expected: Builds successfully.

Following the directions in the error to "Retarget solution" didn't fix the problem. I found a way to update the version by manually editing the project file. Stay tuned. I'll make a pull request with this fix and get feedback on whether we should roll forward to this version and whether my fix looks correct.

**Comment by angelaHillier** [comment]
Your fix has now been merged into Main.
