### ISSUE TITLE
can't capture photos at 1280x720 resolution after using SpatialUnderstanding

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit#73]
This is a duplicate of [issue 520 that I have entered in the HoloToolkit-Unity project](https://github.com/Microsoft/HoloToolkit-Unity/issues/520#issuecomment-281488517) and was advised to enter here as well.

REPRO CASE:
1. Open HoloToolkit-Unity in Unity 5.5.1f1.
2. Create new scene.
3. Create a game object with the atached PhotoCaptureExample.cs script. (This script is based on https://docs.unity3d.com/ScriptReference/VR.WSA.WebCam.PhotoCapture.html, but the resolution is changed to 1280x720.)
4. Add the SpatialMapping prefab to your scene.
5. Add the SpatialUnderstanding prefab to your scene. In the Spatial Understanding component, uncheck the Auto Begin Scanning property.
6. In player settings, publishing, check the WebCam checkbox.
7. Build and run the project on HoloLens.

result: The following error occurs and then the application unexpectedly exists:
Failed to set capture resolution (hr = 0xC00D36B4)
(Filename: C:/buildslave/unity/build/Runtime/VR/HoloLens/WebCam/PhotoCapture.cpp Line: 1180)

expected: PhotoCaptureExample script succeeds and prints "OnCapturedPhotoToMemory succeeded". Note that you can currently get the expected result either by changing the resolution to 2048x1152 or by skipping over the call to SpatialUnderstanding_Init.

You can access a repro case from my fork at https://github.com/ForrestTrepte/HoloToolkit-Unity/tree/issues/520_SpUndPhCap_FailedMinRepro. Use the scene Assets/Issue520.unity.

[PhotoCaptureExample.txt](https://github.com/Microsoft/HoloToolkit/files/791593/PhotoCaptureExample.txt)

**Comment by cstensonpv** [comment]
Hi! I have a similar issue when I'm scanning and even after request_finsih I cant access the camera. It never initializes. Anyone Haveing any idea about why spatialUnderstanding is accessing the camera?

**Comment by ForrestTrepte** [comment]
It appears that this is due to SpatialUnderstanding changing the floating point rounding mode. See https://github.com/Microsoft/HoloToolkit-Unity/issues/520 for more info.

**Comment by ForrestTrepte** [comment]
I'm working on a fix. (This may take a little while if I only get the chance to work on it a little bit each day.)
