### ISSUE TITLE
PlaneFinding.Editor build x64

### ISSUE THREAD

**Issue by HoloFan** [Microsoft/HoloToolkit#87]
Hello,

The HoloToolkit.Unity repro has an PlaneFinding.dll compiled as x64.
But the PlaneFinding.sln does not contain a build configuration for x64.
Is this one missing? What do I have to change to enable a build in x64 to use in the Unity Editor?

Thanks in advance.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/issues/629

**Comment by HoloFan** [comment]
@StephenHodgson : Thanks. But this not quite answers my question. :/
I know that the WSA only needs the x86 dll as the HoloLens runs on x86.
But in order to use the PlaneFinding in the unity editor an x64 dll is required.

At the moment this one is present. i.e. there is a PlaneFinding.dll in each of the following folders:
../SpatialMapping/Plugins/x86
../SpatialMapping/Plugins/x64
../SpatialMapping/Plugins/WSA/x86

Now I am looking for the build settings of the PlaneFinding-Project, to create the x64 dll located currently in the Plugins/x64 folder.

**Comment by StephenHodgson** [comment]
I know it wasn't the answer. I linked them because I thought they were related.

**Comment by HoloFan** [comment]
I got it working by just adding a new Platform and inheriting from x86.
In the Configuration Manager I selected only the PlaneFinding.Editor project to be build when the x64-Platform is selected.
There are some warnings concerning the conversion from size_t to int but it still works.
