### ISSUE TITLE
SpatialUnderstanding TestApp crashes in UniversalDebug configuration

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit#88]
Repro:
1) Get HoloToolkit version 6e72ca9734387757ae079670f04b46f708be6013.
2) Open SpatialUnderstanding\SpatialUnderstanding.sln, set TestApp as your startup project.
3) Build and deploy the UniversalDebug x86 config on your local machine (or HoloLens device).
4) Copy dynMeshTest_0.out test file to LocalState, as described in "Note: To run these tests" comment in MainPage.xaml.cpp.
5) Set a breakpoint on line 207 of MainPage.xaml.cpp. (The call to DebugData_LoadAndSet_DynamicScan_InitScan.)
6) Run the app. Click the "Click Me To Test" button.
   [Your breakpoint is hit.]
7) Debug, Step Into. (Steps into the DebugData_LoadAndSet_DynamicScan_InitScan function.)
RESULT: Unhandled exception at 0x75693992 (ucrtbase.dll) in TestApp.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.  [The call stack is long, so I'll paste it into a separate comment.]
EXPECTED: No crash.

Note that this crash doesn't occur in the UniversalRelease configuration.

**Comment by ForrestTrepte** [comment]
Here is the call stack:
 	ucrtbase.dll!__invoke_watson()	Unknown
 	ucrtbase.dll!__invalid_parameter()	Unknown
 	ucrtbase.dll!__invalid_parameter_noinfo()	Unknown
 	ucrtbase.dll!__XMMI_FP_Emulation()	Unknown
 	ucrtbase.dll!__read_nolock()	Unknown
 	ucrtbase.dll!__fread_nolock_s()	Unknown
 	ucrtbase.dll!_fread_s()	Unknown
 	ucrtbase.dll!_fread()	Unknown
>	SpatialUnderstanding.dll!DebugData_LoadAndSet_DynamicScan_InitScan(_iobuf * f) Line 158	C++
 	TestApp.exe!TestApp::MainPage::RunTest_RealTimeScan_DynamicInputData() Line 219	C++
 	TestApp.exe!TestApp::MainPage::Button_Click(Platform::Object ^ sender, Windows::UI::Xaml::RoutedEventArgs ^ e) Line 77	C++
 	TestApp.exe!`Windows::UI::Xaml::RoutedEventHandler::RoutedEventHandler<TestApp::MainPage,void (__cdecl TestApp::MainPage::*)(Platform::Object ^,Windows::UI::Xaml::RoutedEventArgs ^)>'::`2'::__abi_PointerToMemberWeakRefCapture::Invoke(Platform::Object ^ __param0, Windows::UI::Xaml::RoutedEventArgs ^ __param1)	C++
 	TestApp.exe!Windows::UI::Xaml::RoutedEventHandler::Invoke(Platform::Object ^ __param0, Windows::UI::Xaml::RoutedEventArgs ^ __param1)	C++
 	TestApp.exe!Windows::UI::Xaml::RoutedEventHandler::[Windows::UI::Xaml::RoutedEventHandler::__abi_IDelegate]::__abi_Windows_UI_Xaml_RoutedEventHandler___abi_IDelegate____abi_Invoke(Platform::Object ^ __param0, Windows::UI::Xaml::RoutedEventArgs ^ __param1)	C++
 	Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase<DirectUI::IUntypedEventSource,Windows::UI::Xaml::IRoutedEventHandler,IInspectable,Windows::UI::Xaml::IRoutedEventArgs>::Raise(IInspectable * pSource, Windows::UI::Xaml::IRoutedEventArgs * pArgs) Line 1048	C++
 	Windows.UI.Xaml.dll!DirectUI::ButtonBase::OnClick() Line 889	C++
 	Windows.UI.Xaml.dll!DirectUI::Button::OnClick() Line 91	C++
 	Windows.UI.Xaml.dll!DirectUI::ButtonBase::PerformPointerUpAction() Line 790	C++
 	Windows.UI.Xaml.dll!DirectUI::ButtonBase::OnPointerReleased(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 764	C++
 	Windows.UI.Xaml.dll!DirectUI::ControlGenerated::OnPointerReleasedProtected(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pE) Line 1419	C++
 	Windows.UI.Xaml.dll!DirectUI::Control::FireEvent(KnownEventIndex nDelegate, DirectUI::DependencyObject * pSender, IInspectable * pArgs) Line 261	C++
 	Windows.UI.Xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject * pCoreListener, KnownEventIndex eventId, CDependencyObject * pCoreSender, CEventArgs * pCoreArgs, unsigned int flags) Line 1800	C++
 	Windows.UI.Xaml.dll!CCoreServices::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 3557	C++
 	Windows.UI.Xaml.dll!CommonBrowserHost::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 755	C++
 	Windows.UI.Xaml.dll!CControlBase::ScriptCallback(void * pControl, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pInternalHandler) Line 306	C++
 	Windows.UI.Xaml.dll!CXcpDispatcher::OnScriptCallback(CEventInfo * pEventInfo) Line 1240	C++
 	Windows.UI.Xaml.dll!CXcpDispatcher::OnWindowMessage(HWND__ * msg, unsigned int wParam, unsigned int lParam, long) Line 1092	C++
 	Windows.UI.Xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 746	C++
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@36()	Unknown
 	user32.dll!_DispatchClientMessage@24()	Unknown
 	user32.dll!___fnDWORD@4()	Unknown
 	ntdll.dll!_KiUserCallbackDispatcher@12()	Unknown
 	user32.dll!_SendMessageW@16()	Unknown
 	Windows.UI.Xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest(void * pVoidBH, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pHandler) Line 1070	C++
 	Windows.UI.Xaml.dll!CEventManager::RaiseControlEvents(EventHandle hEvent, CControl * pSender, CEventArgs * pArgs, long(__stdcall*)(void *, CDependencyObject *, EventHandle, CDependencyObject *, CEventArgs *, int, IScriptObject *, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *)) pfnScriptCallback) Line 1117	C++
 	Windows.UI.Xaml.dll!CEventManager::Raise(EventHandle hEvent, int bRefire, CDependencyObject * pSender, CEventArgs * pArgs, bool fRaiseSync, bool fInputEvent, bool bAllowErrorFallback, CDependencyObject * pSenderOverride) Line 861	C++
 	Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEvent(EventHandle hEvent, CDependencyObject * pSource, CRoutedEventArgs * pArgs, bool bIgnoreVisibility, bool fRaiseSync, bool fInputEvent, CDependencyObject * coerceToHandledAtElement) Line 1237	C++
 	Windows.UI.Xaml.dll!CInputManager::RaiseDelayedPointerUpEvent(TouchInteractionMsg * pMsgGesture, CDependencyObject * pElement) Line 5655	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessGestureInput(CDependencyObject * pElement, TouchInteractionMsg * pMsg) Line 5399	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessTouchInteractionCallback(const xref_ptr<CUIElement> & element, TouchInteractionMsg * message) Line 5293	C++
 	Windows.UI.Xaml.dll!CCoreServices::ProcessTouchInteractionCallback(const xref_ptr<CUIElement> & element, TouchInteractionMsg * message) Line 1059	C++
 	Windows.UI.Xaml.dll!CTouchInteractionElement::TouchInteractionCallback(TouchInteractionMsg * message) Line 42	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::InteractionEngineCallback(const INTERACTION_CONTEXT_OUTPUT * pOutputFromICM) Line 808	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::StaticInteractionEngineCallback(void * pvData, const INTERACTION_CONTEXT_OUTPUT * outputFromICM) Line 39	C++
 	ninput.dll!COutputConverter::Process(class CInteractionContextConfiguration const &,enum InteractionContextProperties::MeasurementUnits,enum CInteractionContextGlobal::FeedbackSettings,enum DIGITIZER_KIND,struct tagRECT const &,struct tagRECT const &,struct INTERACTION_INPUT const *,unsigned int,struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!CInteractionContextImpl::OutputCallback(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!CInteractionGroupingFilter::_SendOutput(struct INTERACTION_OUTPUT const &)	Unknown
 	ninput.dll!CInteractionGroupingFilter::Input(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!COutputCoalescingFilter::Flush(void)	Unknown
 	ninput.dll!COutputCoalescingFilter::Input(void *,struct INTERACTION_OUTPUT const *)	Unknown
 	ninput.dll!CInteractionEngineImpl::DigitizerInput(enum DIGITIZER_KIND,unsigned __int64,unsigned int,unsigned int,struct INTERACTION_INPUT const *)	Unknown
 	ninput.dll!CInteractionContextImpl::ProcessFrameHistory(unsigned int,unsigned int,struct tagPOINTER_INFO const *)	Unknown
 	ninput.dll!_ProcessPointerFramesInteractionContext@16()	Unknown
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::ProcessPointerInformation(const InputMessage & msg) Line 913	C++
 	Windows.UI.Xaml.dll!CTouchInteractionHelper::ProcessPointerMessage(const InputMessage & msg) Line 74	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessPointerMessagesWithInteractionEngine(unsigned int pMsg, InputMessage * pInteractionElement, CUIElement * pManipulationElement, CUIElement * bIgnoreManipulationElement, unsigned int pInteractionContext, CTouchInteractionHelper * bForceDisableGesture, unsigned int) Line 4968	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessInteractionPointerMessages(unsigned int pointerId, InputMessage * pMsg) Line 4734	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessPointerInput(InputMessage * pMsg, int * pfHandled, unsigned long hWindowID) Line 3384	C++
 	Windows.UI.Xaml.dll!CInputManager::ProcessInput(InputMessage * pMsg, int * handled, unsigned long hWindowID) Line 1209	C++
 	Windows.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, int * fHandled, unsigned long hWindowID) Line 949	C++
 	Windows.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, bool & fHandled, unsigned long hWindowID) Line 1389	C++
 	Windows.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned int wParam, long lParam) Line 604	C++
 	Windows.UI.Xaml.dll!CJupiterControl::HandleWindowMessage(unsigned int uMsg, unsigned int wParam, long lParam) Line 333	C++
 	Windows.UI.Xaml.dll!CJupiterWindow::CoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 1085	C++
 	Windows.UI.Xaml.dll!CJupiterWindow::StaticCoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 519	C++
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@36()	Unknown
 	user32.dll!_DispatchMessageWorker@8()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(int bDrainQueue, int * pbWindowMessagesProcessed, int * pbInvokeItemProcessed) Line 315	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal(int bRunAlwaysOnce, void * hEventWait) Line 1766	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 569	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 100	C++
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()	Unknown
 	twinapi.appcore.dll!<lambda>(void)()	Unknown
 	SHCore.dll!_WrapperThreadProc()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by jwittner** [comment]
I saw no crashes.
