### ISSUE TITLE
SpatialUnderstanding TestApp Click Me To Test button cannot be seen on HoloLens

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit#89]
Repro:
1) Get HoloToolkit version  6e72ca9.
2) Open SpatialUnderstanding\SpatialUnderstanding.sln, set TestApp as your startup project.
3) Build and run the UniversalDebug x86 config on your HoloLens device.
RESULT: Blank white form. The Click Me To test button from MainPage.xaml is not visible. (Is it positioned offscreen?)
EXPECTED: Click Me To test button is visible and can be clicked to run the test.

**Comment by jwittner** [comment]
Saw it on the emulator.
