### ISSUE TITLE
It isn't obvious if SpatialUnderstanding TestApp succeeded or failed

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/HoloToolkit#95]
When you run TestApp from SpatialUnderstanding.sln and press the Click Me To Test button there is no feedback about whether the test succeeded or failed. I suppose that you would know if it crashed, but there is no verification of correct results and at some places if things aren't working the test silently returns. In order to verify the test, you need to step through the code in the debugger.

**Comment by ForrestTrepte** [comment]
I am considering this approach:
1) Put a results field in MainPage.xaml to show whether the test succeeded or failed.
2) When the test finds an error and returns before completing the test, pass back an error string. (Display string in results field.)
3) Do some very basic checking of the resulting vertex data at the end of RunTest_RealTimeScan_DynamicInputData. I'm not planning to verify which exact vertex values are correct, but I'm thinking of checking that it has returned a minimum number of vertices and that their positions and normal are within a reasonable range.

This won't be a thorough unit test, but will be a quick sanity check that is easy to run.

**Comment by jwittner** [comment]
Saw a successful failure.
